"""Minimal, executor-agnostic Arkx execution contracts and telemetry."""

from .contracts import Event, EventType, ExecutionRecord, ExecutionStatus
from .characterization import (
    CharacterizationConfig,
    Confidence,
    RecommendedPath,
    Scope,
    TaskCharacterization,
    TaskSignals,
    characterize,
    characterize_timed,
)
from .progress import (
    ProgressAssessment,
    ProgressConfig,
    ProgressEvidence,
    ProgressSnapshot,
    ProgressStatus,
    assess_progress,
    assess_progress_timed,
)
from .routing import (
    BudgetState,
    EscalationAction,
    EscalationDecision,
    EvidenceSufficiency,
    RoutingBudget,
    RoutingDecision,
    RoutingDecisionType,
    assess_escalation,
    route_characterization,
)
from .planning import (
    PlanStep,
    ReplanRequest,
    ReplanResult,
    ReplanTrigger,
    RepositoryPlan,
    RepositoryState,
    StepStatus,
    build_plan,
    plan_repository,
)
from .verification import (
    PatchVerificationInput,
    PatchVerificationResult,
    PatchVerificationStatus,
    TestResult,
    TestResultStatus,
    verify_patch,
)
from .handoff import (
    HandoffBudgetStatus,
    HandoffPolicy,
    HandoffRecord,
    HandoffSummary,
    summarize_handoffs,
)
from .composition import (
    ComparabilityStatus,
    ExperimentIdentity,
    ExperimentManifest,
    ExperimentSummary,
    Mechanism,
    Treatment,
    TrialObservation,
    compare_trials,
    initial_manifest,
    summarize_trials,
)
from .executor_qualification import (
    ComparisonAxis,
    ExecutionEnvironment,
    ExecutionOutcome,
    ExecutionBudget,
    ExecutorIdentity,
    ExecutorObservation,
    ExecutorTrial,
    QualificationExperiment,
    QualificationStatus,
    QualificationSummary,
    QualificationTask,
    assess_trial,
    compare_trials as compare_qualification_trials,
    summarize_experiment,
)
from .p82 import (
    P82Comparability, P82Criteria, P82ExperimentConfig, P82ExperimentPlan,
    P82Observation, P82ObservationRecord, P82RunManifest, P82RunStatus, P82Treatment,
    P82TreatmentSummary, P82TrialPlan, TaskSampleManifest, TaskSampleTask, TaskStratum,
    build_p82_plan, compare_run_manifests, p82_manifest, plan_is_comparable, summarize_p82,
)
from .p82_baseline import (
    AcceptanceDecision, AcceptanceResult, BaselineExecutionState, BaselineRunConfig,
    BaselineSampleManifest, ExplicitVerificationAcceptance, ExecutionArtifact,
    MiniSweAgentHeadlessRunner, ProspectiveTask, VerificationResult, VerificationState,
    baseline_observation,
)

__all__ = [
    "Event",
    "EventType",
    "ExecutionRecord",
    "ExecutionStatus",
    "CharacterizationConfig",
    "Confidence",
    "RecommendedPath",
    "Scope",
    "TaskCharacterization",
    "TaskSignals",
    "characterize",
    "characterize_timed",
    "ProgressAssessment",
    "ProgressConfig",
    "ProgressEvidence",
    "ProgressSnapshot",
    "ProgressStatus",
    "assess_progress",
    "assess_progress_timed",
    "BudgetState",
    "EscalationAction",
    "EscalationDecision",
    "EvidenceSufficiency",
    "RoutingBudget",
    "RoutingDecision",
    "RoutingDecisionType",
    "assess_escalation",
    "route_characterization",
    "PlanStep",
    "ReplanRequest",
    "ReplanResult",
    "ReplanTrigger",
    "RepositoryPlan",
    "RepositoryState",
    "StepStatus",
    "build_plan",
    "plan_repository",
    "PatchVerificationInput",
    "PatchVerificationResult",
    "PatchVerificationStatus",
    "TestResult",
    "TestResultStatus",
    "verify_patch",
    "HandoffBudgetStatus",
    "HandoffPolicy",
    "HandoffRecord",
    "HandoffSummary",
    "summarize_handoffs",
    "ComparabilityStatus",
    "ExperimentIdentity",
    "ExperimentManifest",
    "ExperimentSummary",
    "Mechanism",
    "Treatment",
    "TrialObservation",
    "compare_trials",
    "initial_manifest",
    "summarize_trials",
    "ComparisonAxis",
    "ExecutionEnvironment",
    "ExecutionOutcome",
    "ExecutionBudget",
    "ExecutorIdentity",
    "ExecutorObservation",
    "ExecutorTrial",
    "QualificationExperiment",
    "QualificationStatus",
    "QualificationSummary",
    "QualificationTask",
    "assess_trial",
    "compare_qualification_trials",
    "summarize_experiment",
    "P82ExperimentConfig",
    "P82ExperimentPlan",
    "P82Comparability",
    "P82Criteria",
    "P82Observation",
    "P82ObservationRecord",
    "P82RunManifest",
    "P82RunStatus",
    "P82Treatment",
    "P82TreatmentSummary",
    "P82TrialPlan",
    "TaskSampleManifest",
    "TaskSampleTask",
    "TaskStratum",
    "build_p82_plan",
    "compare_run_manifests",
    "p82_manifest",
    "plan_is_comparable",
    "summarize_p82",
    "AcceptanceDecision",
    "AcceptanceResult",
    "BaselineExecutionState",
    "BaselineRunConfig",
    "BaselineSampleManifest",
    "ExplicitVerificationAcceptance",
    "ExecutionArtifact",
    "MiniSweAgentHeadlessRunner",
    "ProspectiveTask",
    "VerificationResult",
    "VerificationState",
    "baseline_observation",
]
