"""Minimal, executor-agnostic CodePro chassis exposed through the arkx namespace."""

__version__ = "0.2.0"

from .contracts import Event, EventType, ExecutionRecord, ExecutionStatus
from .characterization import (
    CharacterizationConfig,
    Confidence,
    RecommendedPath,
    Scope,
    TaskCharacterization,
    TaskSignals,
    characterize,
    characterize_timed,
)
from .progress import (
    ProgressAssessment,
    ProgressConfig,
    ProgressEvidence,
    ProgressSnapshot,
    ProgressStatus,
    assess_progress,
    assess_progress_timed,
)
from .routing import (
    BudgetState,
    EscalationAction,
    EscalationDecision,
    EvidenceSufficiency,
    RoutingBudget,
    RoutingDecision,
    RoutingDecisionType,
    assess_escalation,
    route_characterization,
)
from .planning import (
    PlanStep,
    ReplanRequest,
    ReplanResult,
    ReplanTrigger,
    RepositoryPlan,
    RepositoryState,
    StepStatus,
    build_plan,
    plan_repository,
)
from .verification import (
    PatchVerificationInput,
    PatchVerificationResult,
    PatchVerificationStatus,
    TestResult,
    TestResultStatus,
    verify_patch,
)
from .handoff import (
    HandoffBudgetStatus,
    HandoffPolicy,
    HandoffRecord,
    HandoffSummary,
    summarize_handoffs,
)

__all__ = [
    "__version__",
    "Event",
    "EventType",
    "ExecutionRecord",
    "ExecutionStatus",
    "CharacterizationConfig",
    "Confidence",
    "RecommendedPath",
    "Scope",
    "TaskCharacterization",
    "TaskSignals",
    "characterize",
    "characterize_timed",
    "ProgressAssessment",
    "ProgressConfig",
    "ProgressEvidence",
    "ProgressSnapshot",
    "ProgressStatus",
    "assess_progress",
    "assess_progress_timed",
    "BudgetState",
    "EscalationAction",
    "EscalationDecision",
    "EvidenceSufficiency",
    "RoutingBudget",
    "RoutingDecision",
    "RoutingDecisionType",
    "assess_escalation",
    "route_characterization",
    "PlanStep",
    "ReplanRequest",
    "ReplanResult",
    "ReplanTrigger",
    "RepositoryPlan",
    "RepositoryState",
    "StepStatus",
    "build_plan",
    "plan_repository",
    "PatchVerificationInput",
    "PatchVerificationResult",
    "PatchVerificationStatus",
    "TestResult",
    "TestResultStatus",
    "verify_patch",
    "HandoffBudgetStatus",
    "HandoffPolicy",
    "HandoffRecord",
    "HandoffSummary",
    "summarize_handoffs",
]
