"""Minimal, executor-agnostic CodePro execution contracts and telemetry."""

__version__ = "0.3.0.dev0"

from .contracts import Event, EventType, ExecutionRecord, ExecutionStatus
from .configuration import ConfigurationSnapshot
from .event_log import ChainIntegrity, EventLog, ReferenceReport, ReplayChain, ReplayState, RestoredChainAudit, ResumeAction, ResumeDecision, append_promotion_decision, append_recovery_plan, assess_chain_integrity, audit_restored_chain, classify_chain_references, classify_snapshot_chain_references, decide_resume, replay_chain, replay_events, validate_attempt_lineage_chain, validate_final_chain, validate_outcome_chain, validate_replay_against_manifest, validate_replay_outcomes, validate_replay_telemetry, validate_terminal_replay
from .integration import AdapterIdentity, AdapterPreflight, CapabilityProvenance, DependencyObservation, IntegrationKind, PreflightStatus, assess_preflight, exception_error_envelope, preflight_error, process_error_envelope, provider_error_envelope
from .execution import (
    BudgetConsumption, BudgetLedger, CapabilityProfile, CapabilityRegistry, ExecutionBudgetSpec, ExecutionPlan, ExecutionRequest, ExecutionResult, Executor, FakeExecutor, FakeProvider, FakeSandbox, RetryAttemptPlan, RetryDecision, RetryPolicy, execution_reference, plan_retry_attempt, validate_execution_chain,
    ContractRun, Provider, ProviderRequest, ProviderResponse, Sandbox, SandboxRequest, validate_provider_identity, validate_sandbox_identity,
)
from .harness import AcceptanceEvidence, ArtifactRecord, ArtifactStatus, ArtifactStore, AuditedComparison, AttemptComparison, AttemptEvidence, AttemptSnapshot, AttemptStore, ComparabilityStatus, ComparisonReport, ErrorDomain, ErrorEnvelope, ExperimentRecord, ExperimentSnapshot, LifecycleEvent, PairComparison, RecoveryLineage, RetryLineage, Retryability, RunManifest, RunState, VerificationEvidence, compare_attempt_collection, compare_attempts, derive_attempt_id, derive_experiment_identity_digest, evidence_from_snapshot, load_attempt, load_experiment_record, validate_execution_artifact_consistency, validate_experiment_record, validate_experiment_record_audited, validate_transition, write_experiment_record
from .outcomes import AcceptanceDecision, AcceptanceResult, VerificationResult, VerificationState, validate_outcome_references
from .request import (
    ArkxRequest,
    GovernanceDecision,
    GovernancePolicy,
    GovernanceReason,
    GovernanceStatus,
    RequestBudget,
    RequestEnvironment,
    authorize_request,
    characterize_authorized_request,
)
from .selection import (
    ExecutorBinding,
    ExecutorRegistry,
    SelectionDecision,
    SelectionReason,
    SelectionStatus,
    TreatmentCatalog,
    TreatmentDefinition,
    select_executor,
    select_treatment,
)
from .p82_localization import (
    LocalizationArtifact,
    LocalizationEvidenceBudget,
    record_localization_artifact,
)
from .p82_editing import (
    EditOperation,
    StructuredEditProposal,
    record_edit_proposal,
)
from .orchestration import (
    BudgetEnforcedExecutorRunner,
    ContractExecutorRunner,
    ExecutionOutcome,
    ExecutionResult as OrchestrationExecutionResult,
    OrchestrationReason,
    OrchestrationResult,
    OrchestrationStatus,
    orchestration_status_for_acceptance,
    orchestration_status_for_execution,
    run_routed_pipeline,
)
from .recovery import (
    RecoveryAttemptPlan,
    RecoveryPlan,
    RecoveryAction,
    RecoveryBudget,
    RecoveryDecision,
    RecoveryReason,
    build_recovery_plan, decide_recovery, plan_recovery_attempt, validate_recovery_reference,
)
from .acceptance import AcceptancePolicy, decide_independent_acceptance
from .promotion import (
    PromotionCandidate,
    PromotionDecision,
    PromotionPolicy,
    PromotionReason,
    PromotionStatus,
    decide_outcome_promotion,
    decide_promotion,
    decide_snapshot_promotion,
    load_promotion_decision,
    write_promotion_decision,
)
from .characterization import (
    CharacterizationConfig,
    Confidence,
    RecommendedPath,
    Scope,
    TaskCharacterization,
    TaskSignals,
    characterize,
    characterize_timed,
)
from .progress import (
    ProgressAssessment,
    ProgressConfig,
    ProgressEvidence,
    ProgressSnapshot,
    ProgressStatus,
    assess_progress,
    assess_progress_timed,
)
from .routing import (
    BudgetState,
    CapabilityPolicyDecision,
    CapabilityPolicyReason,
    EscalationAction,
    EscalationDecision,
    EvidenceSufficiency,
    RoutingBudget,
    RoutingDecision,
    RoutingDecisionType,
    assess_escalation,
    assess_capability_policy,
    route_characterization,
)
from .planning import (
    PlanStep,
    ReplanRequest,
    ReplanResult,
    ReplanTrigger,
    RepositoryPlan,
    RepositoryState,
    StepStatus,
    build_plan,
    plan_repository,
)
from .verification import (
    PatchVerificationInput,
    PatchVerificationResult,
    PatchVerificationStatus,
    TestResult,
    TestResultStatus,
    verify_patch,
)
from .handoff import (
    HandoffBudgetStatus,
    HandoffPolicy,
    HandoffRecord,
    HandoffSummary,
    summarize_handoffs,
)
from .composition import (
    ComparabilityStatus,
    ExperimentIdentity,
    ExperimentManifest,
    ExperimentSummary,
    Mechanism,
    Treatment,
    TrialObservation,
    compare_trials,
    initial_manifest,
    summarize_trials,
)
from .executor_qualification import (
    ComparisonAxis,
    ExecutionEnvironment,
    ExecutionOutcome,
    ExecutionBudget,
    ExecutorIdentity,
    ExecutorObservation,
    ExecutorTrial,
    QualificationExperiment,
    QualificationStatus,
    QualificationSummary,
    QualificationTask,
    assess_trial,
    compare_trials as compare_qualification_trials,
    summarize_experiment,
)
from .p82 import (
    P82Comparability, P82Criteria, P82ExperimentConfig, P82ExperimentPlan,
    P82Observation, P82ObservationRecord, P82RunManifest, P82RunStatus, P82Treatment,
    P82TreatmentSummary, P82TrialPlan, TaskSampleManifest, TaskSampleTask, TaskStratum,
    build_p82_plan, compare_run_manifests, p82_manifest, plan_is_comparable, summarize_p82,
)
from .p82_baseline import (
    BaselineExecutionState, BaselineRunConfig,
    BaselineSampleManifest, ExplicitVerificationAcceptance, ExecutionArtifact,
    MiniSweAgentHeadlessRunner, ProspectiveTask, RunnerFailureCategory,
    baseline_observation,
)
from .swebench_authority import (
    AUTHORITY_IDENTITY, DATASET_IDENTITY, DATASET_SPLIT, OfficialEvaluationResult,
    OfficialEvaluationStatus, SWEbenchOfficialAuthority, SWEbenchPrediction, SWEbenchRecord,
    load_verified_records, qualify_gold,
)

__all__ = [
    "Event",
    "EventType",
    "ExecutionRecord",
    "ExecutionStatus",
    "ConfigurationSnapshot",
    "EventLog",
    "AdapterIdentity",
    "AdapterPreflight",
    "CapabilityProvenance",
    "DependencyObservation",
    "IntegrationKind",
    "PreflightStatus",
    "assess_preflight",
    "exception_error_envelope",
    "preflight_error",
    "process_error_envelope",
    "provider_error_envelope",
    "ReplayState",
    "RestoredChainAudit",
    "append_promotion_decision",
    "ReplayChain",
    "ReferenceReport",
    "ChainIntegrity",
    "assess_chain_integrity",
    "replay_chain",
    "classify_chain_references",
    "classify_snapshot_chain_references",
    "replay_events",
    "audit_restored_chain",
    "validate_attempt_lineage_chain",
    "validate_replay_against_manifest",
    "validate_replay_outcomes",
    "validate_replay_telemetry",
    "validate_final_chain",
    "validate_outcome_chain",
    "ExecutionRequest",
    "ExecutionPlan",
    "CapabilityProfile",
    "CapabilityRegistry",
    "ExecutionBudgetSpec",
    "BudgetConsumption",
    "BudgetLedger",
    "RetryDecision",
    "RetryPolicy",
    "RetryAttemptPlan",
    "plan_retry_attempt",
    "execution_reference",
    "validate_execution_chain",
    "ExecutionResult",
    "ContractRun",
    "Executor",
    "Provider",
    "Sandbox",
    "ProviderRequest",
    "ProviderResponse",
    "validate_provider_identity",
    "validate_sandbox_identity",
    "SandboxRequest",
    "FakeExecutor",
    "FakeProvider",
    "FakeSandbox",
    "ErrorDomain",
    "ArtifactStore",
    "AuditedComparison",
    "ArtifactRecord",
    "ArtifactStatus",
    "AttemptSnapshot",
    "AttemptStore",
    "AttemptComparison",
    "AttemptEvidence",
    "VerificationEvidence",
    "AcceptanceEvidence",
    "ExperimentRecord",
    "ExperimentSnapshot",
    "validate_experiment_record",
    "validate_experiment_record_audited",
    "write_experiment_record",
    "load_experiment_record",
    "ComparabilityStatus",
    "compare_attempts",
    "ComparisonReport",
    "PairComparison",
    "compare_attempt_collection",
    "evidence_from_snapshot",
    "LifecycleEvent",
    "ErrorEnvelope",
    "Retryability",
    "RetryLineage",
    "RecoveryLineage",
    "RunManifest",
    "RunState",
    "derive_attempt_id",
    "derive_experiment_identity_digest",
    "validate_transition",
    "validate_execution_artifact_consistency",
    "load_attempt",
    "ArkxRequest",
    "GovernanceDecision",
    "GovernancePolicy",
    "GovernanceReason",
    "GovernanceStatus",
    "RequestBudget",
    "RequestEnvironment",
    "authorize_request",
    "characterize_authorized_request",
    "ExecutorBinding",
    "ExecutorRegistry",
    "SelectionDecision",
    "SelectionReason",
    "SelectionStatus",
    "TreatmentCatalog",
    "TreatmentDefinition",
    "select_executor",
    "select_treatment",
    "ExecutionOutcome",
    "BudgetEnforcedExecutorRunner",
    "ContractExecutorRunner",
    "OrchestrationExecutionResult",
    "OrchestrationReason",
    "OrchestrationResult",
    "OrchestrationStatus",
    "orchestration_status_for_acceptance",
    "orchestration_status_for_execution",
    "run_routed_pipeline",
    "RecoveryAction",
    "RecoveryBudget",
    "RecoveryDecision",
    "RecoveryPlan",
    "RecoveryAttemptPlan",
    "RecoveryReason",
    "decide_recovery",
    "build_recovery_plan",
    "plan_recovery_attempt",
    "validate_recovery_reference",
    "AcceptancePolicy",
    "decide_independent_acceptance",
    "PromotionCandidate",
    "PromotionDecision",
    "PromotionPolicy",
    "PromotionReason",
    "PromotionStatus",
    "decide_outcome_promotion",
    "decide_promotion",
    "CharacterizationConfig",
    "Confidence",
    "RecommendedPath",
    "Scope",
    "TaskCharacterization",
    "TaskSignals",
    "characterize",
    "characterize_timed",
    "ProgressAssessment",
    "ProgressConfig",
    "ProgressEvidence",
    "ProgressSnapshot",
    "ProgressStatus",
    "assess_progress",
    "assess_progress_timed",
    "BudgetState",
    "CapabilityPolicyDecision",
    "CapabilityPolicyReason",
    "EscalationAction",
    "EscalationDecision",
    "EvidenceSufficiency",
    "RoutingBudget",
    "RoutingDecision",
    "RoutingDecisionType",
    "assess_escalation",
    "assess_capability_policy",
    "route_characterization",
    "PlanStep",
    "ReplanRequest",
    "ReplanResult",
    "ReplanTrigger",
    "RepositoryPlan",
    "RepositoryState",
    "StepStatus",
    "build_plan",
    "plan_repository",
    "PatchVerificationInput",
    "PatchVerificationResult",
    "PatchVerificationStatus",
    "TestResult",
    "TestResultStatus",
    "verify_patch",
    "HandoffBudgetStatus",
    "HandoffPolicy",
    "HandoffRecord",
    "HandoffSummary",
    "summarize_handoffs",
    "ComparabilityStatus",
    "ExperimentIdentity",
    "ExperimentManifest",
    "ExperimentSummary",
    "Mechanism",
    "Treatment",
    "TrialObservation",
    "compare_trials",
    "initial_manifest",
    "summarize_trials",
    "ComparisonAxis",
    "ExecutionEnvironment",
    "ExecutionOutcome",
    "ExecutionBudget",
    "ExecutorIdentity",
    "ExecutorObservation",
    "ExecutorTrial",
    "QualificationExperiment",
    "QualificationStatus",
    "QualificationSummary",
    "QualificationTask",
    "assess_trial",
    "compare_qualification_trials",
    "summarize_experiment",
    "P82ExperimentConfig",
    "P82ExperimentPlan",
    "P82Comparability",
    "P82Criteria",
    "P82Observation",
    "P82ObservationRecord",
    "P82RunManifest",
    "P82RunStatus",
    "P82Treatment",
    "P82TreatmentSummary",
    "P82TrialPlan",
    "TaskSampleManifest",
    "TaskSampleTask",
    "TaskStratum",
    "build_p82_plan",
    "compare_run_manifests",
    "p82_manifest",
    "plan_is_comparable",
    "summarize_p82",
    "AcceptanceDecision",
    "AcceptanceResult",
    "BaselineExecutionState",
    "BaselineRunConfig",
    "BaselineSampleManifest",
    "ExplicitVerificationAcceptance",
    "ExecutionArtifact",
    "MiniSweAgentHeadlessRunner",
    "ProspectiveTask",
    "RunnerFailureCategory",
    "VerificationResult",
    "VerificationState",
    "validate_outcome_references",
    "baseline_observation",
    "AUTHORITY_IDENTITY",
    "DATASET_IDENTITY",
    "DATASET_SPLIT",
    "OfficialEvaluationResult",
    "OfficialEvaluationStatus",
    "SWEbenchOfficialAuthority",
    "SWEbenchPrediction",
    "SWEbenchRecord",
    "load_verified_records",
    "qualify_gold",
]
